version: "3.7"

networks:
    example:
        external: true

services:
    hello-world:
        deploy:
            mode: global
        image: "${IMAGE_TAG:?}"
        labels:
            traefik.enable: "true"
            traefik.http.services.happy-now.loadbalancer.server.port: 8080
            traefik.http.middlewares.https-only.redirectscheme.scheme: "https"
            traefik.http.routers.happy-now.rule: "Host(`happy-now.salamandra.powerman.name`)"
            traefik.http.routers.happy-now.middlewares: "https-only"
            traefik.http.routers.happy-now-tls.rule: "Host(`happy-now.salamandra.powerman.name`)"
            traefik.http.routers.happy-now-tls.tls: "true"
            traefik.http.routers.happy-now-tls.service: "happy-now"
        networks:
            example:
